version: '3.8'

services:
  qdrant-local:
    image: qdrant/qdrant:latest
    container_name: qdrant-local
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  api:
    build: .
    container_name: api
    ports:
      - "8087:8000"
    environment:
      - QDRANT_HOST=qdrant-local
      - QDRANT_PORT=6333
      # - QDRANT_API_KEY=  # Uncomment jika menggunakan API key
    volumes:
      - ./uploads:/app-knowledge/uploads
    depends_on:
      - qdrant-local
    restart: unless-stopped

volumes:
  qdrant_storage:
